# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\AYŞENUR\OneDrive\Masaüstü\Visual-Programming-PyQT-Lecture-Notes\soru\soruseç.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Sorulari_Gor = QtWidgets.QTableWidget(self.centralwidget)
        self.Sorulari_Gor.setGeometry(QtCore.QRect(0, 0, 901, 192))
        self.Sorulari_Gor.setObjectName("Sorulari_Gor")
        self.Sorulari_Gor.setColumnCount(7)
        self.Sorulari_Gor.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Sorulari_Gor.setHorizontalHeaderItem(6, item)
        self.Dosya_Sec = QtWidgets.QPushButton(self.centralwidget)
        self.Dosya_Sec.setGeometry(QtCore.QRect(70, 480, 371, 51))
        self.Dosya_Sec.setObjectName("Dosya_Sec")
        self.Yazdir = QtWidgets.QPushButton(self.centralwidget)
        self.Yazdir.setGeometry(QtCore.QRect(480, 480, 371, 51))
        self.Yazdir.setObjectName("Yazdir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Soru Bankasından Soru Seçimi"))
        item = self.Sorulari_Gor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Soru"))
        item = self.Sorulari_Gor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1. seçenek"))
        item = self.Sorulari_Gor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2. seçenek"))
        item = self.Sorulari_Gor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "3. seçenek"))
        item = self.Sorulari_Gor.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "4. seçenek"))
        item = self.Sorulari_Gor.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "5. seçenek"))
        item = self.Sorulari_Gor.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Cevap"))
        self.Dosya_Sec.setText(_translate("MainWindow", "Yazdırılacak soru bankasına ait dosyayı seçiniz"))
        self.Yazdir.setText(_translate("MainWindow", "Yazdır"))
