# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\AYŞENUR\OneDrive\Masaüstü\Visual-Programming-PyQT-Lecture-Notes\soru\SoruBankası.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 448, 26))
        self.menubar.setObjectName("menubar")
        self.menu_lem = QtWidgets.QMenu(self.menubar)
        self.menu_lem.setObjectName("menu_lem")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.SoruEkle_SayfasGe = QtWidgets.QAction(MainWindow)
        self.SoruEkle_SayfasGe.setObjectName("SoruEkle_SayfasGe")
        self.SoruSe_Sayfas = QtWidgets.QAction(MainWindow)
        self.SoruSe_Sayfas.setObjectName("SoruSe_Sayfas")
        self.menu_lem.addAction(self.SoruEkle_SayfasGe)
        self.menu_lem.addAction(self.SoruSe_Sayfas)
        self.menubar.addAction(self.menu_lem.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Soru Bankası "))
        self.menu_lem.setTitle(_translate("MainWindow", "İşlem "))
        self.SoruEkle_SayfasGe.setText(_translate("MainWindow", "Yeni Soru Ekle"))
        self.SoruSe_Sayfas.setText(_translate("MainWindow", "Soru Seç"))
